baseURL = 'https://www.kelrys.com/'
languageCode = 'en-gb'
title = 'PowerShell and other technologies...'
theme = 'mainroad'
enableRobotsTXT = true
DefaultContentLanguage = "en"
googleAnalytics = ""
[blackfriday]
  hrefTargetBlank = false
[params]
  subtitle = 'My adventures in IT'
  enableLightDarkTheme = true
  permanentTopNav = true
  stickyNav = true
  toc = true
  baseColor = "#ff8080"
  siteWidth = "2000px"
  css_modules = ["//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css"]
  js_modules = ["//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js","init-cookieconsent.js"]
  author = "Andrew Davidson"
  description = "PowerShell and other technologies... blog"
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"
  paginate = 5
  enable_mathjax = false
  algolia_search = false
  resizeImages = true
  gravatarEMail = "github@kelrys.com"
  customImage = "/images/andrewD_256.png"
  overlayIcon = "fa-home"
  showHeaderLanguageChooser = true
  enableMomentJs = true
  dateFormat = "RFC1123"
  dateForm = "RFC1123"
  showReadingTime = false
  tocMinWordCount = 400
  showFooter = true
  amountLatestPostsInFooter = 7
  amountCategoriesInFooter = 7
  showFooterLanguageChooser = true
  showSocialMedia = false
  showArchive = true
  archiveDateGrouping = "2006-01"
  
  copyrightBy = "by Andrew Davidson"
  copyrightUseCurrentYear = true
  copyrightYearOverride = "2017"
  copyrightUrl = "https://github.com/andrewrdavidson"
  creditsText = "."
  creditsUrl = "."
